# Site settings
assets:
  cachebust: hard
title: Jeff Triplett
name: Jeff Triplett
email: jeff.triplett@gmail.com
description: >
  Thoughts about life, technology, development, and blog by Jeff Triplett.
baseurl: ""
url: "https://jefftriplett.com"
enforce_ssl: "jefftriplett.com"
relative_permalinks: false
permalink: :year/:title/  # permalink: date
future: true
paginate: 100

plugins:
  # - jekyll-archives
  # - jekyll-coffeescript
  # - jekyll-crosspost-to-medium
  # - octopress-autoprefixer
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

include:
  - _pages

exclude:
  - "*/src/*"
  - .bumpversion.cfg
  - .gitignore
  - .vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Procfile
  - README.md
  - Rakefile
  - _pages/categories.html
  - _pages/tags.html
  - docker-compose.yml
  - jekyll.dockerapp
  - modd.conf
  - node_modules
  - package*.json
  - plugins
  - purgecss.config.js
  - requirements.txt
  - staticman.yml

markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: compressed

collections:  # process the _data folder
  components:
    output: false
  playlists:
    output: true
    permalink: /:collection/:name/
  projects:
    output: false
    permalink: /:collection/:name/
  topics:
    output: true
    permalink: /:collection/:name/

defaults:  # Frontmatter fallback settings
  - scope:
      path: ""
    values:
      image: /assets/images/dcus-2017-bw.jpg

# Amazon Tracking ID

amazon_affiliate_id: webology0b-20

# SEO Plugin settings

author: webology

facebook:
  app_id: 182545102225662

logo: /assets/images/dcus-2017-bw.jpg

social:
  name: Jeff Triplett
  links:
    - https://github.com/jefftriplett
    - https://hub.docker.com/u/jefftriplett/
    - https://keybase.io/jefftriplett
    - https://mastodon.social/@webology
    - https://medium.com/@webology
    - https://open.spotify.com/user/jefftriplett
    - https://pinboard.in/u:jefftriplett
    - https://twitter.com/webology
    - https://www.buymeacoffee.com/webology
    - https://www.facebook.com/jefftriplett
    - https://www.flickr.com/photos/webology
    - https://www.indiehackers.com/user/jeff
    - https://www.instagram.com/jefftriplett/
    - https://www.myfitnesspal.com/profile/jefftriplett

twitter:
  username: "webology"

# Needed for the default template... not sure if they are used anywhere else
github_username: jefftriplett
twitter_username: "webology"

# Jekyll Mentions

jekyll-mentions:
  base_url: https://twitter.com

# Jekyll to Medium

jekyll-crosspost_to_medium:
  backdate: true
  #cache: .jekyll-crosspost_to_medium
  enabled: true
  license: all-rights-reserved
  status: draft
  text: '<p><i>Your (optional) signoff for the post.</i></p>'

# Custom vars
version: 0.19.0
google-fonts-family: PT+Serif:400,400italic,700|PT+Sans:400|Alegreya
